# ENPH 213 - Week 4 Lab
In this lab, we will be working on solving systems of linear equations using the Gaussian Elimination method while continuing to develop your Python skills.

When you are finished, please rename this notebook to LastName_ENPH213_Lab4, where LastName is your last name.  Submit that file to onQ.

For marking Parts 1-4 will be marked together (Weighted out of 10) and Parts 5 and 6 will be marked together (Weighted out of 5).

## Part 1

Write a function $GaussPivot(Ab, col)$ that inputs an augmented matrix $Ab$ of an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  The $col$ input to the function is the column that of the pivot element to be assessed.  For this Part, the goal is to simulate finding those rows that would need to be pivoted in a Gaussian Elimination procedure, and no "zeroing" of columns is needed.  Remember that for a generic column $col$ input, a pivot point of $A_{jj}$ means that the pivot row is the same index as the column being reduced and only rows below $A_{jj}$ need to be considered.

Start with the following arrays. 

$A = \begin{bmatrix}
    10 & 9 & 8 & 7 \\
    1  & 2 & 3 & 4 \\
    6  & 6 & 3 & 2 \\
    1  & 5 & 4 & 7
\end{bmatrix}
,\ \ \ b = \begin{bmatrix}
    6  \\
    5  \\
    1  \\
    9  
\end{bmatrix}$

When using the augmented matrix $Ab$, the pivoted matrices I calculated are (for $col = 0, 1, 2$)

$Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    1  & 2 & 3 & 4 & 5\\
    6  & 6 & 3 & 2 & 1\\
    1  & 5 & 4 & 7 & 9
\end{bmatrix}
,Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    6  & 6 & 3 & 2 & 1\\
    1  & 2 & 3 & 4 & 5\\
    1  & 5 & 4 & 7 & 9
\end{bmatrix}
,Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    1  & 2 & 3 & 4 & 5\\
    1  & 5 & 4 & 7 & 9\\
    6  & 6 & 3 & 2 & 1
\end{bmatrix}$

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
%matplotlib inline

In [2]:
# initalize the arrays given
A = np.array([[10, 9, 8, 7],[1, 2, 3, 4], [6, 6, 3, 2], [1, 5, 4, 7]])
b = np.array([[6, 5, 1, 9]])

#now get Ab
Ab = np.concatenate([A,np.transpose(b)], 1) # addding b to a new col
OG = np.copy(Ab) #saving the original array
print(Ab) #checking the Ab array

[[10  9  8  7  6]
 [ 1  2  3  4  5]
 [ 6  6  3  2  1]
 [ 1  5  4  7  9]]


In [3]:
# function for Gauss Pivot
def GaussPivot(Ab , col):
    #goal is to simulate the rows that need to be pivoted
    if ((np.max(Ab[col:,col])) > (Ab[col,col])): # test codition for swapping rows
       
        Ab[[col,np.argmax(Ab[col:,col]) + col],:] = Ab[[np.argmax(Ab[col:,col]) + col,col], :] #swapping rows
        
    return Ab


    #if(Ab[col][col]<Ab[col][col+1]): 
        
        #Ab[[col,col+1],:] = Ab[[col+1,col],:] 
        
    

Ab = OG # setting the array back to it's original form

print("\n Pivoting the rows for Ab for Column",0,"\n",GaussPivot(Ab,0))

print("\n Pivoting the rows for Ab for Column",1,"\n",GaussPivot(Ab,1))

print("\n Pivoting the rows for Ab for Column",2,"\n",GaussPivot(Ab,2))



 Pivoting the rows for Ab for Column 0 
 [[10  9  8  7  6]
 [ 1  2  3  4  5]
 [ 6  6  3  2  1]
 [ 1  5  4  7  9]]

 Pivoting the rows for Ab for Column 1 
 [[10  9  8  7  6]
 [ 6  6  3  2  1]
 [ 1  2  3  4  5]
 [ 1  5  4  7  9]]

 Pivoting the rows for Ab for Column 2 
 [[10  9  8  7  6]
 [ 6  6  3  2  1]
 [ 1  5  4  7  9]
 [ 1  2  3  4  5]]


## Part 2

Write a function GaussElim(Ab, col) that inputs an augmented matrix $Ab$ of an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  The $col$ input to the function is the column that of the pivot element, which will have zeros underneath.  For this Part, the goal is to only have zeros under the first pivot element ($A_{00}$), so col = 0.  It does _not_ have to put the matrix in triangular form.  Pivoting should be included in the function using the $GaussPivot(Ab, col)$ function above.

When I entered the $Ab$ array from Part 1, I got the result:

$Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    0  & 1.1 & 2.2 & 3.3 & 4.4 \\
    0  & 0.6 & -1.8 & -2.2 & -2.6\\
    0  & 4.1 & 3.2 & 6.3 & 8.4
\end{bmatrix}$

In [4]:
# initalize givens and reset Ab array
col = 0

Ab = np.concatenate([A,np.transpose(b)], 1) 
Ab = Ab.astype(float) #setting Ab back to what it was but now floats
Ab # test to see if it is correct 

array([[10.,  9.,  8.,  7.,  6.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  6.,  3.,  2.,  1.],
       [ 1.,  5.,  4.,  7.,  9.]])

In [5]:
# function to do matrix operations under the pivot

def GaussElim(Ab,col):
    #call the pivot func
    Ab1 = GaussPivot(Ab, col)
    Nrows = Ab.shape[0]  # set the bounds of the loop to the rows in the array
    
    # loop through the array and use the eqn given
    # row i = row i - Aij/Ajj * row j
    for i in range(col+1, Nrows):
       
        Ab1[i][:] = Ab1[i][:]-(Ab1[i][col]/(np.copy(Ab1[col][col])))*Ab1[col][:]
    
    return Ab1


print("\n Ab for Column",0,"\n",GaussElim(Ab,0)) # test func with print




 Ab for Column 0 
 [[10.   9.   8.   7.   6. ]
 [ 0.   1.1  2.2  3.3  4.4]
 [ 0.   0.6 -1.8 -2.2 -2.6]
 [ 0.   4.1  3.2  6.3  8.4]]


## Part 3

Write a third function UpTriang(A, b) that inputs an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  This function should output an augmented matrix in upper triangular form.  In UpTriang(A, b), call the GaussElim(Ab, col) function you created above and index over the appropriate $col$ values.  The $col$ values should not be set, but instead should be derived from the size of $A$.  Using the $A$ and $b$ arrays above, my code generated the following outputs at the next two steps in the elimination process (decimals trucated).

$A = \begin{bmatrix}
10 &   9 &  8&  7&    6 \\
0  &  4.1& 3.2  &6.3  &  8.4  \\
0  &   0 &  -2.268 & -3.12195 & -3.829268 \\
0  &   0 &  1.341 &  1.6097 &  2.1463 
\end{bmatrix}$

$A = \begin{bmatrix}
10 &   9 &  8&  7&    6 \\
0  &  4.1& 3.2  &6.3  &  8.4  \\
0  &   0 &  -2.268 & -3.12195 & -3.829268 \\
0  &   0 &  0 &  -0.236559 &  -0.11828  
\end{bmatrix}$

If everything is working except for your pivoting, then you should see

$A = \begin{bmatrix}
10 &   9 &  8&  7&    6 \\
0  &  1.1& 2.2  &3.3  &  4.4  \\
0  &   0 &  -3 & -4 & -5 \\
0  &   0 &  0 & 0.6667 &  0.3333 
\end{bmatrix}$

In [6]:
A = np.array([[10, 9, 8, 7],[1, 2, 3, 4], [6, 6, 3, 2], [1, 5, 4, 7]])
b = np.array([[6, 5, 1, 9]])

A = A.astype(float) #setting Ab back to what it was but now floats
b = b.astype(float) #setting Ab back to what it was but now floats

In [7]:

def UpTriang(A, b):
    
    column = A.shape[0] # number of col
    
    Ab = np.concatenate([np.array(A),np.transpose(np.array(b))], 1) # making the new array with b on A
  
    copy = np.copy(Ab) # copying the array
    
    for i in range(column): # looping through the array
        copy = GaussElim(copy,i) # calling our elim func for increasing columns
        
    return copy

In [8]:
print("Upper Triangle of Ab\n",UpTriang(A,b)) # test func with print


Upper Triangle of Ab
 [[10.          9.          8.          7.          6.        ]
 [ 0.          4.1         3.2         6.3         8.4       ]
 [ 0.          0.          1.34146341  1.6097561   2.14634146]
 [ 0.          0.          0.         -0.4        -0.2       ]]


## Part 4

Finally, write a function $BackSub(A, b)$ that inputs an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  This function should call the $UpTriang(A, b)$ function and then use Back Substitution from the lecture to solve the system of equations $\mathbf{Ax=b}$.  This function should output a 1-D array of values that correspond to the $x_i$ in the $\mathbf x$ array.  To check your answer, substitute $\mathbf x$ into $\mathbf{Ax=b}$ to recover the values in $\mathbf b$.

In [9]:
A = np.array([[10, 9, 8, 7],[1, 2, 3, 4], [6, 6, 3, 2], [1, 5, 4, 7]])
b = np.array([[6, 5, 1, 9]])
A = A.astype(float)
b = b.astype(float)

In [10]:
# function should output a 1-D array of values that correspond to the xi, in the x array
# inputs the A and b arrays
# solvs the sytstem of equations using Back Sub

def BackSub(A,b):
    
    upperA = UpTriang(A,b) # call the Uptriangle Func
    
    for i in range(A.shape[0]): # loop through for num columns
        
        upperA[i,:] = upperA[i,:]/upperA[i,i]
        
    copy = np.copy(upperA) # make a copy of array
    
    # nest for loops to iterate throught the array
    for a in range(upperA.shape[0]-1,-1,-1):
        
        for b in range(a-1,-1,-1):
            
            copy[b,:] = copy[b,:]-upperA[a,:]*upperA[b,a] # subtract and set new value
            
            upperA = np.copy(copy)
            
            newArray = upperA[:,A.shape[0]] 
    return newArray


    

In [11]:

testArray = BackSub(A,b) # check the function by calling it with A and b
print("The Solution for the system of eqns is\n",testArray) # print the result
sizeB = np.size(b) # find the size of array b to iterate through
check = np.ones(sizeB) # initalize the check array


sumb = np.sum(b[0,:]) # taking the sum of b
#print(sumb)

sumA = np.sum(testArray*A[0:sizeB,:]) # multiplying the result by A, for N rows
#print(sumA)

# now need to check if there is an actual solution
check = sumb - sumA
check = check.astype(int)
#print(check)

# Conditional prints
if (check == 0): 
    print("\nThe Solution is Correct")
else:
    print("\nNot a True Soln")

The Solution for the system of eqns is
 [-1.   0.5  1.   0.5]

The Solution is Correct


## Part 5

You now have all the tools to write a function to return the inverse of a matrix.  Write a function $myInv(A)$ that inputs an $N \times N$ matrix/2D array $A$ and returns its inverse.  You can work with the array $A$ above, and to verify that your new matrix is indeed the inverse, evaluate $\mathbf{ A A^{-1} = I}$.

Q: If your $\mathbf{ A A^{-1} = I}$ is not exactly the identity matrix, please explain why?

In [12]:
def myInv(A):
    N = A.shape
    I = np.array(np.zeros(N))
    for i in range (N[0]):
        I[i,i] = 1
    Aup = UpTriang(A,I)
    for i in range(N[0]):
        Aup[i,:] = Aup[i,:]/Aup[i,i]
    Atest = np.copy(Aup)
    for x in range(N[0]-1,-1,-1):
        for y in range(x-1,-1,-1):
            Atest[y,:] = Aup[y,:]-Aup[x,:]*Aup[y,x]
            Aup = np.copy(Atest)
    return Aup[:,4:]

print("A:\n",A,"\n\nA^(-1):\n",myInv(A),"\n\n")
print("A*A^(-1):\n",np.matmul(myInv(A),A),"\n")

# There resultant matrix of A*A^(-1) is not perfectly the identity matrix because rounding errors
# populate the zero values with very small values. This noise can be eliminated by rounding the 
# values to the nearest integer, resulting in the identity matrix
Rounded = (np.around(np.matmul(myInv(A),A))).astype(int)
print("A*A^(-1) Rounded :\n",Rounded)

A:
 [[10.  9.  8.  7.]
 [ 1.  2.  3.  4.]
 [ 6.  6.  3.  2.]
 [ 1.  5.  4.  7.]] 

A^(-1):
 [[ 1.54545455 -3.45454545 -2.          1.        ]
 [-1.04545455  1.95454545  1.5        -0.5       ]
 [-2.18181818  5.81818182  3.         -2.        ]
 [ 1.77272727 -4.22727273 -2.5         1.5       ]] 


A*A^(-1):
 [[ 1.00000000e+00 -5.55111512e-16 -1.33226763e-15 -4.32986980e-15]
 [ 6.21724894e-15  1.00000000e+00  6.21724894e-15  7.99360578e-15]
 [-4.44089210e-16 -5.77315973e-15  1.00000000e+00 -1.33226763e-15]
 [-4.66293670e-15 -2.22044605e-16 -8.88178420e-16  1.00000000e+00]] 

A*A^(-1) Rounded :
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
# function to return the inverse of an N by N matrix
# takes one input, the array
def myInv(A):

    col = A.shape[0] #number of col
       
    I_array = np.array(np.zeros(A.shape)) # initalize the inverse array with 0's
    
    for i in range (col):
        I_array[i,i] = 1 # put 1's along the diagonal
        
    #print(I_array) #test print
   
    upperA = UpTriang(A,I_array) # call the upper triangle function
    
    # Now need to take the inverse of the array
  
    for i in range(col):
        upperA[i,:] = upperA[i,:]/upperA[i,i] 
        
    #print(upperA) #test print
        
    copy = np.copy(upperA) # take the copy of the new array
    
    for a in range(col-1,-1,-1): # nested loops through the array
        
        for b in range(a-1,-1,-1):
            
            copy[b,:] = upperA[b,:]-upperA[a,:]*upperA[b,a]
            upperA = np.copy(copy)
            
    inverse = upperA[:,4:] #take all rows and the col after 4
    
    return inverse


Ab = np.concatenate([A,np.transpose(b)], 1) 
Ab = Ab.astype(float) #setting Ab back to what it was but now floats
Ab # test to see if it is correct 

print(" Originl A array:\n",A) #checking the Ab array

print("\n\n Array inversed A^(-1):\n",myInv(A)) # printing the inverse

mul = np.matmul(myInv(A),A) # multiplying the arrays
      
print("\n Array Multiplied by inverse:\n A*A^(-1):\n",mul,"\n") # printing the exact result

# there is a small diference that has to do with the rounding and imerfections of comoutation
# by taking the rounded version one can see the function did infact work
round = (np.around(mul)).astype(int)

print("A*A^(-1) Rounded :\n",round)

 Originl A array:
 [[10.  9.  8.  7.]
 [ 1.  2.  3.  4.]
 [ 6.  6.  3.  2.]
 [ 1.  5.  4.  7.]]


 Array inversed A^(-1):
 [[ 1.54545455 -3.45454545 -2.          1.        ]
 [-1.04545455  1.95454545  1.5        -0.5       ]
 [-2.18181818  5.81818182  3.         -2.        ]
 [ 1.77272727 -4.22727273 -2.5         1.5       ]]

 Array Multiplied by inverse:
 A*A^(-1):
 [[ 1.00000000e+00 -5.55111512e-16 -1.33226763e-15 -4.32986980e-15]
 [ 6.21724894e-15  1.00000000e+00  6.21724894e-15  7.99360578e-15]
 [-4.44089210e-16 -5.77315973e-15  1.00000000e+00 -1.33226763e-15]
 [-4.66293670e-15 -2.22044605e-16 -8.88178420e-16  1.00000000e+00]] 

A*A^(-1) Rounded :
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Part 6

Write a another function UpTriang2(A, b) that inputs an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  This function should output an augmented matrix in upper triangular form.  In UpTriang2(A, b), call the GaussElim(Ab, col) function you created above as you did before, but instead of indexing over the appropriate $col$ values, remove the Row 0 and Column 0 parts of the array to create a slightly smaller array.  [Note, you should store the Row 0 value to create the upper triangular matrix.]  Then run GaussElim(Ab, col), for col=0, on this new smaller array, save Row 0, create a smaller array, and iterate until Gaussian Elimination is complete.  Test you algorithm against the $A$ and $b$ you used above.

There is a thought that by working on smaller arrays, this method to create upper triangular matrices could be faster.  Test this idea by creating a large array of $1000 \times 1000$ random values and create an upper triangular array use the two functions you have created.  Time their performance using the %timeit command before calling the functions. [Note: $b$ will need to be a 2D array of $1 \times 1000$ elements.  "Up-Size" the array by using np.array([np.random.rand(100)]).

Q: Briefly discuss which function was faster and hypothesize why.  Also, time your functions for $100 \times 100$ and $10 \times 10$ input arrays.  How does the run-time change for changing N?  Does this make sense?  Consider this relative to the approximate number of calculations your function has to do.

In [14]:
# function to reduce the computing time of UpTriang
# does this by sending smaller and smaller arrays to Elim

def UpTriang2(A,b):
    Ab = np.concatenate([A, np.transpose(b)],1) # reassign array Ab
    copy = np.copy(Ab) # make a copy of Ab
    
    rows = np.zeros(copy.shape) #array of zeros same size and Ab
    #print(rows) #test print
    
    for i in range(copy.shape[0]): # loop through the array
        
        copy = GaussElim(copy,0) # call the Elim function
        
        rows[i,i:] = copy[0,:] 
        
        copy = copy[1:,1:] #make the copy a smaller ver of the array to be sent
        
    return rows

# To test this function I compare it's output to that of the previous UpTriang function

print("Arrays to compare the functions:\n\tA\n",A,"\n\n\tb\n",b)

print("\nComputed with the first function\n",UpTriang(A,b))
print("\n\nComputed with the 2nd function\n",UpTriang2(A,b))

print("\n\n We can see these are equivalent")


Arrays to compare the functions:
	A
 [[10.  9.  8.  7.]
 [ 1.  2.  3.  4.]
 [ 6.  6.  3.  2.]
 [ 1.  5.  4.  7.]] 

	b
 [[6. 5. 1. 9.]]

Computed with the first function
 [[10.          9.          8.          7.          6.        ]
 [ 0.          4.1         3.2         6.3         8.4       ]
 [ 0.          0.          1.34146341  1.6097561   2.14634146]
 [ 0.          0.          0.         -0.4        -0.2       ]]


Computed with the 2nd function
 [[10.          9.          8.          7.          6.        ]
 [ 0.          4.1         3.2         6.3         8.4       ]
 [ 0.          0.          1.34146341  1.6097561   2.14634146]
 [ 0.          0.          0.         -0.4        -0.2       ]]


 We can see these are equivalent


In [15]:
# if you dont want to visually compare can use a conditional

if (np.array_equal(UpTriang2(A,b),UpTriang(A,b))):
    print("\nOne can see the Functions are Equal")


One can see the Functions are Equal


In [16]:
#Now Need to compare the functions big O

# can declare random arrays and test the speeds of the 2 functions

N = 1000

rand1 = np.random.rand(N,N) # random N by N array
#print(rand1) #test print

R = np.array([np.random.rand(N)]) # random N array
#print(R) #test print

In [17]:
%timeit UpTriang(rand1,R) #time of func 1

6.9 s ± 702 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
%timeit UpTriang2(rand1,R) #time of func 2

5.9 s ± 443 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
# Now we can test the functions using 100 random points
N = 100
rand2 = np.random.rand(N,N)
R2 = np.array([np.random.rand(N)])

In [20]:
%timeit UpTriang(rand2,R2) # Test func 1

41.9 ms ± 2.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%timeit UpTriang2(rand2,R2) # Test func 2

49.9 ms ± 5.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
# Now we can test the functions using 10 random points
N = 10
rand3 = np.random.rand(N,N)
R3 = np.array([np.random.rand(N)])

In [23]:
%timeit UpTriang(rand3,R3)

624 µs ± 53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [24]:
%timeit UpTriang2(rand3,R3)

709 µs ± 64.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Q: Briefly discuss which function was faster and hypothesize why. Also, time your functions for  100×100  and  10×10  input arrays. How does the run-time change for changing N? Does this make sense? Consider this relative to the approximate number of calculations your function has to do

A: When handling large matrices, the UpTriang2 function is faster than the UpTriang function since (in the 2nd function) each step reduces the number of computations by taking out unnecessary rows and columns. This is particularly prevalent with very large matrices because the UpTriang2 function performs tens of thousands less calculations in the last few cycles of the loop. The difference in computational time is much smaller for smaller sets of data, as expected. 

## Acknowledgements

Please comment on any help that you received from your group members or others concerning this Lab assignment.

Although I wrote all the code myself I discussed the topics with Stuart Gaherty 