# ENPH 213 - Week 2 Lab - Part 6

Part 6 of the lab seemed more involved and warranted a new notebook.  Please complete it separately, and rename this notebook to LastName_ENPH213_Lab2-Part6, where LastName is your last name.  Submit this file along with the first notebooks containing Parts 1 through5 to onQ.

Of course, please reminder that you are expected to complete your lab using your own code that you have written.

In [1]:
# Importing the libraries
import math as m
import numpy as np
import cmath as cm
from matplotlib import pyplot as plt

## Introduction

In keeping with the theme of magnetics, the goal here is to calculate the force between two cylindrical magnets as part of the design of a magnetic levitation system.  As a first step, you will use the following expression, which gives the magnetic field at location $(x_1, y_1, z_1)$ due to a cylindrical magnet centred on the $z$-axis with its base in the $x-y$ plane.

$\Large B(x_1, y_1, z_1) = \frac{\mu_o}{4 \pi} {\displaystyle \int_0^D \int_0^{2 \pi}} \frac{\vec K \times \vec r}{|r|^3} R d\phi dz$

which you may recognize as Biot-Savart's Law.  In this equation, the magnet has a thickness $D$, radius $R$, and uniform magnetization parallel to the z-axis. The magnetization produces a uniform bound surface current $\vec K$ on the outside surface of the cylinder flowing in the $\hat\phi$-direction, which is the angular direction around the circular magnet.  It is this bound surface current on the edge of the cylindrical magnetic that is responsible for the magnetic field produced by the magnet.  The above equation for the magnetic field is written using Griffith’s notation, where $r$ is the separation vector from the points where the current is located to where we are evaluating the field:

$\Large \vec r = (x_1 - R\cos\phi)\hat x + (y_1 - R\sin\phi)\hat y + (z_1 - z)\hat z$

where $R$, $\phi$, and $z$ are where on the cylinder the surface current is flowing that we are considering.  Similarly, the vectorized surface current density can be written as:

$\Large \vec K = K (-\sin\phi~\hat x + \cos \phi~\hat y)$

By expressing the separation vector and surface current density using unit vectors in Cartesian 
coordinates, you can break the vector integral into three scalar integrals, one for each component of the 
magnetic field.  For example, the $x$-component of the magnetic field $B_x$ can be expressed as a ordinary 
double integral of a scalar function of the $\hat x$-term in Biot-Savart's Law, which we can call BiotSavX$(x_1,y_1,z_1,\phi,z)$.  $B_x$ will then have the integral form:

$\Large B_x (x_1, y_1, z_1) = {\displaystyle \int_0^D \int_0^{2 \pi}} \textrm{BiotSavX}(x_1,y_1,z_1,\phi,z) d\phi dz$

where

$\Large \textrm{BiotSavX}(x_1,y_1,z_1,\phi,z) = \frac{\mu_o R}{4 \pi |r|^3} (\vec K \times \vec r) \cdot \hat x$ 

Rather than using a numerical cross product and then an inner (dot) product with $\hat x$, it is easier to do the $\hat x$ operatio manually, which then just requires you to calculate the $x$-component of the cross product.  This term simply reduced to $K_y r_z - K_z r_y$, where the $K$ and $r$ components cane be seen in the above equations:
$ K_y = K \cos \phi \\
K_z = 0 \\
r_y = y_1-R\sin\phi \\
r_z = z_1 - z$

## Part 6.1

Create your scalar functions for each of the componets of the Biot-Savart integral.  In particular, create functions for each of BiotSavX, BiotSavY, and BiotSavZ.  Use the following input values:

$ R=0.025~m \\ K=0.95 \times 10^6~A/m \\ \mu_o = 4 \pi \times 10^{-7}~N/A^2$

Using the follwing values as input:

$x_1=0.01~m, y_1=0.02~m, z_1=0.03~m, \phi=\pi/6, z=0.05~m$

My code gave an output of:

BiotSavX(0.01,0.02,0.03,$\pi/6$,0.05) = -2.85598

BiotSavY(0.01,0.02,0.03,$\pi/6$,0.05) = -1.64890

BiotSavZ(0.01,0.02,0.03,$\pi/6$,0.05) =  1.04536
 
Once you are getting correct values for BiotSavX, BiotSavY, and BiotSavZ, put them all together in a function called 
BiotSav$(x_1,y_1,z_1,\phi,z)$ that outputs an array of [BiotSavX, BiotSavY, BiotSavZ].

Note, it is important to consider that the functions are vectorized and can process arrays.  It is therefore important to use the Numpy functions appropriately.

In [2]:
# given values for input
R = 0.025 #meters
K = 0.95*10**6 #A/m
mu = 4*np.pi*10**(-7) #N/A^2

x1 = 0.01 #m
y1 = 0.02 #m
z1 = 0.03 #m
phi = np.pi/6 #rad
z = 0.05 #m

In [3]:
# Given relations from the question
Ky = K*np.cos(phi)
Kz = 0
Kx = -K*np.sin(phi)

ry = y1 - R*np.sin(phi)
rz = z1 - z
rx = x1-R*np.cos(phi)

rmag = np.sqrt(ry**2 + rz**2 + rx**2) #magnitude of the r vector

K_vector = [Kx, Ky, Kz]
r_vector = [rx, ry, rz]

$\Large \textrm{BiotSavX}(x_1,y_1,z_1,\phi,z) = \frac{\mu_o R}{4 \pi |r|^3} (\vec K \times \vec r) \cdot \hat x$ 

$\Large \textrm{BiotSavY}(x_1,y_1,z_1,\phi,z) = \frac{\mu_o R}{4 \pi |r|^3} (\vec K \times \vec r) \cdot \hat y$ 

$\Large \textrm{BiotSavZ}(x_1,y_1,z_1,\phi,z) = \frac{\mu_o R}{4 \pi |r|^3} (\vec K \times \vec r) \cdot \hat z$ 

In [57]:
#uses the given equations for BioSav
def BiotSav(x1, y1, z1, phi, z):
    
    #calculating the BiotSav for X Y Z
    
    BiotSavX = (mu*R)/(4*np.pi*rmag**3)*np.dot([np.cross(K_vector,r_vector)],[1,0,0])
    print("The Biot-Savart's Law in X is", BiotSavX)
    
    BiotSavY = (mu*R)/(4*np.pi*rmag**3)*np.dot([np.cross(K_vector,r_vector)],[0,1,0])
    print("The Biot-Savart's Law in Y is", BiotSavY)
    
    BiotSavZ = (mu*R)/(4*np.pi*rmag**3)*np.dot([np.cross(K_vector,r_vector)],[0,0,1])
    print("The Biot-Savart's Law in Z is", BiotSavZ)
    array = [BiotSavX[0], BiotSavY[0], BiotSavZ[0]]
    return array

print("\nThe vector for BiotSav is", BiotSav(x1, y1, z1, phi, z))

The Biot-Savart's Law in X is [-2.85598327]
The Biot-Savart's Law in Y is [-1.64890271]
The Biot-Savart's Law in Z is [1.04536243]

The vector for BiotSav is [-2.8559832672799326, -1.6489027081651355, 1.045362428607738]


## Part 6.2

Next, write a function that evaluates the three components $[B_x,B_y,B_z]$ of the magnetic field at the point $(x_1,y_1,z_1)$ by performing the numerical integration of the Biot Savart Law.  For this part, use the dimensions of the magnet $R=0.025~m$ and $D=0.05~m$. 

Use the linspace function from Numpy to create 2D arrays for the $\phi$ and z-coordinates over which you will be integrating.  Note from the integrals, $0 \leq \phi \leq 2\pi$ and $0 \leq z \leq D$.  Use the Weigthing Arrays for Simpson's Rule, calculate each term of the integral (ie., $B_x$, $B_y$, and $B_z$) separately.  For the $\phi$ and $z$ arrays, identify which ones occupy which coordinate axis in the arrays and remember to define their step sizes (hphi and hz). To check your answer, using N=11 along each axis and $x_1$ = 0.03, $y_1$ = 0.02, and $z_1$= 0.01 (m), my code gave:

$B_x = -0.09344 \\
B_y = -0.06362 \\
B_z = -0.19007 $


In [58]:
#Given Values
R = 0.025 #m
D = 0.05 #m
N = 11

x1 = 0.03 #m
y1 = 0.02 #m
z1 = 0.01 #m

mu = 4*np.pi*10**(-7) #N/A^2

phi_low = 0          #Setting the Bounds
phi_high = np.pi*2

#calc widths
hphi = (phi_high-phi_low)/(N-1) # N points gives N-1 regions

hz = ((D-0)/(N-1)) # same as hPhi but with z

# create a set of points within limits
phiRange = np.linspace(phi_low,phi_high,N) #points for phi
zRange = np.linspace(0,D,N)                #points for z

phiPoints , zPoints = np.meshgrid(phiRange, zRange)

array2D = np.linspace(start=[phi_low,0],stop=[phi_high,D], num = N)  # 2D array of points

print("\tThe array of values\n\tPhi\t\tZ\n",array2D) #displays the array


	The array of values
	Phi		Z
 [[0.00000000e+00 0.00000000e+00]
 [6.28318531e-01 5.00000000e-03]
 [1.25663706e+00 1.00000000e-02]
 [1.88495559e+00 1.50000000e-02]
 [2.51327412e+00 2.00000000e-02]
 [3.14159265e+00 2.50000000e-02]
 [3.76991118e+00 3.00000000e-02]
 [4.39822972e+00 3.50000000e-02]
 [5.02654825e+00 4.00000000e-02]
 [5.65486678e+00 4.50000000e-02]
 [6.28318531e+00 5.00000000e-02]]


## We were given the relation
$\Large B_x (x_1, y_1, z_1) = {\displaystyle \int_0^D \int_0^{2 \pi}} \textrm{BiotSavX}(x_1,y_1,z_1,\phi,z) d\phi dz$
### Can use the equation from 6.1

In [30]:
#uses the given equations for BioSav
# the functions use many similar operations to 6.1

def BiotSavX(phi,z):
    
    Ky = K*np.cos(phi)
    Kz = 0
    Kx = -K*np.sin(phi)

    ry = y1 - R*np.sin(phi)
    rz = z1 - z
    rx = x1-R*np.cos(phi)

    rmag = np.sqrt(ry**2 + rz**2 + rx**2)
    # given relation for x
    cross_x = Ky*rz

    BiotSavX = (mu*R)/(4*np.pi*rmag**3)*cross_x
    #print("\nBiotSavX",BiotSavX)
    
    return BiotSavX

def BiotSavY(phi,z):
    
    Ky = K*np.cos(phi)
    Kz = 0
    Kx = -K*np.sin(phi)

    ry = y1 - R*np.sin(phi)
    rz = z1 - z
    rx = x1-R*np.cos(phi)

    rmag = np.sqrt(ry**2 + rz**2 + rx**2)
    #cross prod for y
    cross_y = -Kx*rz

    BiotSavY = (mu*R)/(4*np.pi*rmag**3)*cross_y
    #print("\nBiotSavY",BiotSavY)
    
    return BiotSavY

def BiotSavZ(phi,z):
    
    Ky = K*np.cos(phi)
    Kz = 0
    Kx = -K*np.sin(phi)

    ry = y1 - R*np.sin(phi)
    rz = z1 - z
    rx = x1-R*np.cos(phi)

    rmag = np.sqrt(ry**2 + rz**2 + rx**2)
    #cross prod for Z
    cross_z = Kx*ry-Ky*rx

    BiotSavZ = (mu*R)/(4*np.pi*rmag**3)*cross_z
    #print("\nBiotSavZ",BiotSavZ)
    
    return BiotSavZ


In [23]:
#Need the weighted array
newWeights = np.ones(N) # weight vector with ones
newWeights[1:N:2] = 4 # adding 4's 1, 3, 5
newWeights[2:-2:2] = 2 # Adding 2's in the array 
newWeights = np.outer(newWeights,newWeights) # expands the dimension of the array (2D)
print("The Weighted Array\n",newWeights) #displays array

The Weighted Array
 [[ 1.  4.  2.  4.  2.  4.  2.  4.  2.  4.  1.]
 [ 4. 16.  8. 16.  8. 16.  8. 16.  8. 16.  4.]
 [ 2.  8.  4.  8.  4.  8.  4.  8.  4.  8.  2.]
 [ 4. 16.  8. 16.  8. 16.  8. 16.  8. 16.  4.]
 [ 2.  8.  4.  8.  4.  8.  4.  8.  4.  8.  2.]
 [ 4. 16.  8. 16.  8. 16.  8. 16.  8. 16.  4.]
 [ 2.  8.  4.  8.  4.  8.  4.  8.  4.  8.  2.]
 [ 4. 16.  8. 16.  8. 16.  8. 16.  8. 16.  4.]
 [ 2.  8.  4.  8.  4.  8.  4.  8.  4.  8.  2.]
 [ 4. 16.  8. 16.  8. 16.  8. 16.  8. 16.  4.]
 [ 1.  4.  2.  4.  2.  4.  2.  4.  2.  4.  1.]]


In [56]:
# Calling the functions with the generated points
FpointsX = (BiotSavX(phiPoints, zPoints)) 
FpointsY = (BiotSavY(phiPoints, zPoints))
FpointsZ = (BiotSavZ(phiPoints, zPoints))


intgX = (hphi*hz)/9*np.sum(FpointsX*newWeights) #multiply points by weight and take dot prod times the widths

intgY = (hphi*hz)/9*np.sum(FpointsY*newWeights) #multiply points by weight and take dot prod times the widths

intgZ = (hphi*hz)/9*np.sum(FpointsZ*newWeights) #multiply points by weight and take dot prod times the widths

print("\nThe double BX integral is",intgX) # final statement X
print("\nThe double BY integral is",intgY) # final statement Y
print("\nThe double BZ integral is",intgZ) # final statement Z


The double BX integral is -0.09343631807138224

The double BY integral is -0.06361657773379946

The double BZ integral is -0.19006951631897429


## Part 6.3

You should now be ready to calculate the force between two cylindrical magnets. Assume that the first magnet sits with its base in the $x-y$ plane and is centred on the z-axis, which is what we have calculated above.  Then, assume that a second, identical cylindrical magnet is placed directly above the first so that the bottom face of the top magnet is a 
distance $d$ above the top face of the bottom magnet (ie., the air gap between the magnets is d). You can the use the Lorentz force law to calculate the force exerted on the second magnet. The expression is given by:

$\Large \vec F (d) = {\displaystyle \int_{D+d}^{2D+d} \int_0^{2 \pi}} \vec K \times \vec B\ R d\phi dz$


Here, $\vec B$ is the magnetic field produced by the first magnet (on the bottom) on the surface of the second magnet, and $\vec K$ is the current density on the surface of the second magnet (top). Note that the limits of $z$ go from $D+d$ to $2D+d$.  The expression for $\vec K$ on the surface of the top magnet is:

$\Large \vec K = -K (-\sin\phi~\hat x + \cos \phi~\hat y)$

where the sign of $\vec K$ has been changed compared to the first magnet. If not, the magnetic fields of the two magnets would be aligned, and the force would be attractive, which would not be very useful for magnetic levitation.

You will be able to use the code and functions above in the Jupyter Notebook (from 6.1 and 6.2), which will allow you to calculate the magnetic field produced by the bottom magnet at each location on the surface of the top magnet. On the surface (the outer round surface where the surface current is) of the top magnet, it is easy to show that $x = R\cos(\phi)$ and $y=R\sin(\phi)$, so the magnetic field is evaluated at $(R\cos(\phi), R\sin(\phi), z)$, where $0 \leq \phi \leq 2\pi$ and $D+d \leq z \leq 2D+d$. To evaluate this new integral, you can create the arrays using the techniques implemented above for the $\phi$ and $z$ variables.  However, you may want to use a nested for loop to calculate each point by first calculating $\vec B$ and then using that to calculate the contributing element to the force.

In [54]:
#New Function for Magnetic Field
def magField(x1,y1,z1):
    #same relations from 6.2/6.2
    Ky = K*np.cos(phi)
    Kz = 0
    Kx = -K*np.sin(phi)

    ry = y1 - R*np.sin(phi)
    rz = z1 - z
    rx = x1-R*np.cos(phi)

    rmag = np.sqrt(ry**2 + rz**2 + rx**2)
    
    cross_x = Ky*rz
    BiotSavX = (mu*R)/(4*np.pi*rmag**3)*cross_x
    
    cross_y = -Kx*rz
    BiotSavY = (mu*R)/(4*np.pi*rmag**3)*cross_y
    
    cross_z = Kx*ry-Ky*rx
    BiotSavZ = (mu*R)/(4*np.pi*rmag**3)*cross_z
    
    magField = [BiotSavX, BiotSavY, BiotSavZ] #returns the array of x,y,z values for the magField
    return magField

#print(magField(x1,y1,z1)) #test print


In [55]:
# d = 0.005 m, this was a correction to the lab

#Main function to get the force vector
def force(d):
    #Given Values
    D = 0.05
    N = 11
    phi_low = 0          #Setting the Bounds
    phi_high = np.pi*2

    #calc widths
    hphi = (phi_high-phi_low)/(N-1) # N points gives N-1 regions

    hz = ((D-0)/(N-1)) # same as hPhi but with z

    # create a set of points within limits
    phiRange = np.linspace(phi_low,phi_high,N) #points for phi
    zRange = np.linspace(D+d,2*D + d,N)                #points for z

    phiPoints , zPoints = np.meshgrid(phiRange, zRange)
    
    newWeights = np.ones(N) # weight vector with ones
    newWeights[1:N:2] = 4 # adding 4's 1, 3, 5
    newWeights[2:-2:2] = 2 # Adding 2's in the array 
    newWeights = np.outer(newWeights,newWeights) # expands the dimension of the array (2D)
    
    valueArray = np.ones((11,11,3)) # 11, 3 x 11 arrays of ones
    
    #need the nested for loop operations
    for i in range(N):
        for a in range(N):
            
            # magnetic field with the given relations for x,y,z
            B = magField(R*np.cos(phiRange[i]), R*np.sin(phiRange[i]), zRange[a]) 
            
            # k array with given relations and specify the float
            k = -K*np.array([-np.sin(phiRange[i]), np.cos(phiRange[i]), 0], dtype = float)
            
            # mul the value Array by the cross of K x B and R * weighted matirx
            valueArray[i,a] = np.cross(k,B)*newWeights[i,a]*R
   
    # Mul the array by the widths/9      
    valueArray *= hphi*hz/9
    
    return valueArray.sum((0,1))
    
print("\tThe Force vector is\n",force(0.005)) #send the force func d


	The Force vector is
 [ 386.08513188  273.54071929 9033.53648261]


## Acknowledgements
Although I wrote all the code in this lab myself I discussed the problems of this portion with the following students:
Ekin Yelken, Stuart Gaherty and Connor Legg